# Generated by Django 5.2.6 on 2026-07-08 00:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('type_device', models.CharField(choices=[('TBEAM', 'T-Beam'), ('LORA', 'LoRa'), ('GPS', 'GPS Tracker')], default='TBEAM', max_length=50)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('ERREUR', 'En erreur')], default='ACTIF', max_length=20)),
                ('batterie', models.FloatField(blank=True, null=True)),
                ('date_activation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_dernier_contact', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type_zone', models.CharField(choices=[('PATURAGE', 'Pâturage'), ('STABULATION', 'Stabulation'), ('ZONE_RISQUE', 'Zone à risque'), ('ZONE_INTERDITE', 'Zone interdite')], default='PATURAGE', max_length=50)),
                ('polygone', models.TextField()),
                ('couleur', models.CharField(default='#FF0000', max_length=7)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_animal', models.CharField(choices=[('VACHE', 'Vache'), ('TAUREAU', 'Taureau'), ('VEAU', 'Veau'), ('BREBIS', 'Brebis'), ('CHEVRE', 'Chèvre')], default='VACHE', max_length=50)),
                ('race', models.CharField(blank=True, max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('PERDU', 'Perdu'), ('MORT', 'Mort')], default='ACTIF', max_length=20)),
                ('date_dernier_contact', models.DateTimeField(blank=True, null=True)),
                ('emoji', models.CharField(default='🐄', max_length=10)),
                ('couleur', models.CharField(default='#4CAF50', max_length=7)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animaux.device')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('batterie', models.FloatField(blank=True, null=True)),
                ('satellites', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('course', models.FloatField(blank=True, null=True)),
                ('raw_data', models.TextField(blank=True)),
                ('format_donnees', models.CharField(default='GPS', max_length=50)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animaux.animal')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('BATTERIE_FAIBLE', 'Batterie faible'), ('HORS_ZONE', 'Hors zone autorisée'), ('INACTIVITE', 'Inactivité prolongée'), ('MORT', 'Animal immobile'), ('ERREUR_GPS', 'Erreur GPS')], max_length=50)),
                ('priorite', models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=20)),
                ('message', models.TextField()),
                ('resolue', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animaux.animal')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animaux.position')),
            ],
        ),
    ]
