# Generated by Django 4.2.11 on 2025-10-16 11:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='priorite',
            field=models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('URGENT', 'Urgente')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='date_activation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animaux.position'),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte',
            field=models.CharField(choices=[('BATTERIE_FAIBLE', 'Batterie faible'), ('HORS_ZONE', 'Hors zone autorisée'), ('INACTIVITE', 'Inactivité prolongée'), ('MORT', 'Animal immobile'), ('ERREUR_GPS', 'Erreur GPS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='couleur',
            field=models.CharField(default='#4CAF50', max_length=7),
        ),
        migrations.AlterField(
            model_name='animal',
            name='emoji',
            field=models.CharField(default='🐄', max_length=10),
        ),
        migrations.AlterField(
            model_name='animal',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('PERDU', 'Perdu'), ('MORT', 'Mort')], default='ACTIF', max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='type_animal',
            field=models.CharField(choices=[('VACHE', 'Vache'), ('TAUREAU', 'Taureau'), ('VEAU', 'Veau'), ('BREBIS', 'Brebis'), ('CHEVRE', 'Chèvre')], default='VACHE', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('ERREUR', 'En erreur')], default='ACTIF', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='type_device',
            field=models.CharField(choices=[('TBEAM', 'T-Beam'), ('LORA', 'LoRa'), ('GPS', 'GPS Tracker')], default='TBEAM', max_length=50),
        ),
        migrations.AlterField(
            model_name='position',
            name='format_donnees',
            field=models.CharField(default='GPS', max_length=50),
        ),
        migrations.AlterField(
            model_name='position',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='position',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='position',
            name='satellites',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='position',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='zone',
            name='polygone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='zone',
            name='type_zone',
            field=models.CharField(choices=[('PATURAGE', 'Pâturage'), ('STABULATION', 'Stabulation'), ('ZONE_RISQUE', 'Zone à risque'), ('ZONE_INTERDITE', 'Zone interdite')], default='PATURAGE', max_length=50),
        ),
    ]
