# Generated by Django 6.0.7 on 2026-07-15 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='code_appairage',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='device',
            name='date_appairage',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='est_appaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zone',
            name='animaux',
            field=models.ManyToManyField(blank=True, related_name='zones', to='animaux.animal'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='polygone',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
