# Generated by Django 6.0.7 on 2026-07-15 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0004_device_code_appairage_device_date_appairage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ELEVEUR', 'Éleveur'), ('ADMIN', 'Administrateur'), ('VETERINAIRE', 'Vétérinaire / Employé partagé')], default='ELEVEUR', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profils/')),
                ('langue', models.CharField(default='fr', max_length=5)),
                ('notif_canal', models.CharField(choices=[('app', 'Application'), ('email', 'E-mail'), ('sms', 'SMS')], default='app', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
