# Generated by Django 6.0.7 on 2026-07-16 12:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0005_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='animaux',
        ),
        migrations.AddField(
            model_name='animal',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animaux_zone', related_query_name='animal_zone', to='animaux.zone'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='emoji',
            field=models.CharField(default='fa-paw', max_length=10),
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONNEXION_ADMIN', 'Connexion admin'), ('CONNEXION_ADMIN_ECHOUEE', 'Connexion admin échouée'), ('CREATION_UTILISATEUR', 'Création utilisateur'), ('MODIFICATION_UTILISATEUR', 'Modification utilisateur'), ('SUPPRESSION_UTILISATEUR', 'Suppression utilisateur'), ('CHANGEMENT_ROLE', 'Changement de rôle'), ('CREATION_COLLIER', 'Création collier'), ('MODIFICATION_COLLIER', 'Modification collier'), ('SUPPRESSION_COLLIER', 'Suppression collier'), ('CHANGEMENT_STATUT_SIGNALEMENT', 'Changement statut signalement vol'), ('AUTRE', 'Autre')], max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('detail', models.TextField(blank=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux_auteur', to=settings.AUTH_USER_MODEL)),
                ('utilisateur_cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux_cible', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignalementVol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('EN_COURS', 'En cours'), ('RESOLU', 'Résolu'), ('FAUX', 'Faux signalement')], default='NOUVEAU', max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animaux.animal')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animaux.position')),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_vol', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
