# Generated by Django 6.0.7 on 2026-07-16 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0006_remove_zone_animaux_animal_zone_alter_animal_emoji_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS animaux_zone_animaux;",
            reverse_sql="SELECT 1;",
        ),
        migrations.AddField(
            model_name='animal',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animaux_zone', related_query_name='animal_zone', to='animaux.zone'),
        ),
    ]
