# Generated by Django 6.0.7 on 2026-07-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animaux', '0007_fix_animal_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='type_alerte',
            field=models.CharField(choices=[('BATTERIE_FAIBLE', 'Batterie faible'), ('HORS_ZONE', 'Hors zone autorisée'), ('INACTIVITE', 'Inactivité prolongée'), ('MORT', 'Animal immobile'), ('ERREUR_GPS', 'Erreur GPS'), ('SIGNAL_FAIBLE', 'Signal faible')], max_length=50),
        ),
    ]
