"""
Django settings for suivi_betail project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

import os
from pathlib import Path

from decouple import Csv, config

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = config('SECRET_KEY', default='django-insecure-ollchq(q=(@z2t!o5t_k%_(706@^13$51jeglvx*93!9oht2t')
DEBUG = config('DEBUG', default=True, cast=bool)

# Configuration Firebase
#FIREBASE_SERVICE_ACCOUNT = os.path.join(BASE_DIR, 'firebase-service-account.json')

#FIREBASE_CONFIG = {
  #  "apiKey": "AIzaSyAz48dr6Ph7makxSCtOGsS7ctxokqBnrhI",
  #  "authDomain": "suivi-betail-dagas.firebaseapp.com",
 #   "projectId": "suivi-betail-dagas",
 #   "storageBucket": "suivi-betail-dagas.firebasestorage.app",
 #   "messagingSenderId": "719860294955",
 #   "appId": "1:719860294955:web:beae1f311ee131ee8d116e",
 #   "databaseURL": "https://suivi-betail-dagas-default-rtdb.firebaseio.com",
  #  "measurementId": "G-VH3B5259KB"
#}

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS CORRIGÉ
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1', 
    '192.168.131.193',  # MON IP
    '192.168.190.193',
    '0.0.0.0',
    '*',  # Pour le développement seulement
]

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'animaux',
    'channels',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'suivi_betail.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'suivi_betail.wsgi.application'

# Database
# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# REST Framework configuration - CORRIGÉ
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Changé pour permettre l'accès sans auth
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'position_create': '100/minute',
    }
}

# CORS configuration
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://192.168.131.193:8000",
    "http://0.0.0.0:8000",
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Dakar'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Channels configuration
ASGI_APPLICATION = 'suivi_betail.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Configuration MQTT Meshtastic
#MESHTASTIC_MQTT_BROKER = 'localhost'
#MESHTASTIC_MQTT_PORT = 1883
#MESHTASTIC_MQTT_USERNAME = ''
#MESHTASTIC_MQTT_PASSWORD = ''

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Configuration supplémentaire pour le développement
if DEBUG:
    # Logging plus détaillé
    LOGGING['root']['level'] = 'DEBUG'

# Configuration MQTT
MQTT_CONFIG = {
    'BROKER_HOST': 'broker.emqx.io',
    'BROKER_PORT': 1883,
    'KEEPALIVE': 60,
    'TOPIC': 'suivi_betail/gps',
}

# Configuration LoRa pour Sénégal
LORA_CONFIG = {
    'FREQUENCY': 868000000,  # 868 MHz pour Afrique
    'BANDWIDTH': 125000,     # 125 kHz
    'SPREADING_FACTOR': 12,  # SF12 pour plus de portée
    'GATEWAY_IP': '192.168.172.193',  # IP de votre gateway
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000

# URL de connexion si l'utilisateur n'est pas authentifié
LOGIN_URL = '/connexion/'

# URL vers laquelle l'utilisateur est redirigé après connexion
LOGIN_REDIRECT_URL = '/dashboard/'  # ou '/' si tu veux l'accueil

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
